// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI_s78IgIrMNOkN2PSydyrLwwJg5nI2zs',
    appId: '1:928748820187:web:f0394b1c41b131dc935efe',
    messagingSenderId: '928748820187',
    projectId: 'fatora-ac6f7',
    authDomain: 'fatora-ac6f7.firebaseapp.com',
    storageBucket: 'fatora-ac6f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbhggqmHIE-6hCxHSMxFq3g00xxlflYSo',
    appId: '1:928748820187:android:0fb9b019178e783c935efe',
    messagingSenderId: '928748820187',
    projectId: 'fatora-ac6f7',
    storageBucket: 'fatora-ac6f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL_1CvsCYk630NwjV8RI3ULJ77DTGpaRs',
    appId: '1:928748820187:ios:b1172a8b9e0af1a7935efe',
    messagingSenderId: '928748820187',
    projectId: 'fatora-ac6f7',
    storageBucket: 'fatora-ac6f7.firebasestorage.app',
    iosBundleId: 'com.example.fatora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL_1CvsCYk630NwjV8RI3ULJ77DTGpaRs',
    appId: '1:928748820187:ios:b1172a8b9e0af1a7935efe',
    messagingSenderId: '928748820187',
    projectId: 'fatora-ac6f7',
    storageBucket: 'fatora-ac6f7.firebasestorage.app',
    iosBundleId: 'com.example.fatora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI_s78IgIrMNOkN2PSydyrLwwJg5nI2zs',
    appId: '1:928748820187:web:1973bd470d246097935efe',
    messagingSenderId: '928748820187',
    projectId: 'fatora-ac6f7',
    authDomain: 'fatora-ac6f7.firebaseapp.com',
    storageBucket: 'fatora-ac6f7.firebasestorage.app',
  );
}
