// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_lKgTcnzNq2Q0swklyGIMkfN214lqUQ',
    appId: '1:631217389920:web:a76d6b1eb59defdd381e05',
    messagingSenderId: '631217389920',
    projectId: 'fatora-dec33',
    authDomain: 'fatora-dec33.firebaseapp.com',
    storageBucket: 'fatora-dec33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYsVnZ6wbNIFJ4sOejLic3VTaP5EKF9ag',
    appId: '1:631217389920:android:ed97e47a5c7a919a381e05',
    messagingSenderId: '631217389920',
    projectId: 'fatora-dec33',
    storageBucket: 'fatora-dec33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7OwUfTSchhpMpNJxjDOPc4_47kza9dgM',
    appId: '1:631217389920:ios:2af8b975201207e4381e05',
    messagingSenderId: '631217389920',
    projectId: 'fatora-dec33',
    storageBucket: 'fatora-dec33.firebasestorage.app',
    iosBundleId: 'com.example.fatora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7OwUfTSchhpMpNJxjDOPc4_47kza9dgM',
    appId: '1:631217389920:ios:2af8b975201207e4381e05',
    messagingSenderId: '631217389920',
    projectId: 'fatora-dec33',
    storageBucket: 'fatora-dec33.firebasestorage.app',
    iosBundleId: 'com.example.fatora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ_lKgTcnzNq2Q0swklyGIMkfN214lqUQ',
    appId: '1:631217389920:web:e8a7265cfa57f2ec381e05',
    messagingSenderId: '631217389920',
    projectId: 'fatora-dec33',
    authDomain: 'fatora-dec33.firebaseapp.com',
    storageBucket: 'fatora-dec33.firebasestorage.app',
  );

}